//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutbolZamani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtkinlikKatilim
    {
        public int ID { get; set; }
        public Nullable<int> EtkinlikID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual Etkinlik Etkinlik { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
