//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutbolZamani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etkinlik()
        {
            this.EtkinlikKatilim = new HashSet<EtkinlikKatilim>();
        }
    
        public int EtkinlikID { get; set; }
        public string EtkinlikAdres { get; set; }
        public string EtkinlikTarih { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> EtkinlikKontenjan { get; set; }
        public string EtkinlikBilgi { get; set; }
        public Nullable<int> EtkinlikDurum { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtkinlikKatilim> EtkinlikKatilim { get; set; }
    }
}
