//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutbolZamani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciProfil
    {
        public int KullaniciID { get; set; }
        public Nullable<int> MacSayisi { get; set; }
        public Nullable<int> GolSayisi { get; set; }
        public Nullable<int> AsistSayisi { get; set; }
        public Nullable<int> ProfilPuani { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
