//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutbolZamani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Arkadas = new HashSet<Arkadas>();
            this.Etkinlik = new HashSet<Etkinlik>();
            this.EtkinlikKatilim = new HashSet<EtkinlikKatilim>();
        }
    
        public int KullaniciID { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public string KullaniciTel { get; set; }
        public string KullaniciAdres { get; set; }
        public string KullaniciMail { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> KullaniciFCM { get; set; }
        public string UserName { get; set; }
        public string Resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arkadas> Arkadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etkinlik> Etkinlik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtkinlikKatilim> EtkinlikKatilim { get; set; }
        public virtual KullaniciProfil KullaniciProfil { get; set; }
    }
}
